// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZsfuvNNlDG0KUVsBsCjKYbxwQ86bximI',
    appId: '1:646751155063:web:fb40cc285a168d6dcb2772',
    messagingSenderId: '646751155063',
    projectId: 'frenzy-2a03e',
    authDomain: 'frenzy-2a03e.firebaseapp.com',
    storageBucket: 'frenzy-2a03e.appspot.com',
    measurementId: 'G-TXD8FF0HDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANgkt68tyaX1JjWXilLGq29mG7yQU520E',
    appId: '1:646751155063:android:97af0d862c36956dcb2772',
    messagingSenderId: '646751155063',
    projectId: 'frenzy-2a03e',
    storageBucket: 'frenzy-2a03e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-a--cF90Gd75yo8vyK58XzU7XCTb8Vfo',
    appId: '1:646751155063:ios:de4b6620483d6968cb2772',
    messagingSenderId: '646751155063',
    projectId: 'frenzy-2a03e',
    storageBucket: 'frenzy-2a03e.appspot.com',
    iosBundleId: 'com.example.frenzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-a--cF90Gd75yo8vyK58XzU7XCTb8Vfo',
    appId: '1:646751155063:ios:de4b6620483d6968cb2772',
    messagingSenderId: '646751155063',
    projectId: 'frenzy-2a03e',
    storageBucket: 'frenzy-2a03e.appspot.com',
    iosBundleId: 'com.example.frenzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZsfuvNNlDG0KUVsBsCjKYbxwQ86bximI',
    appId: '1:646751155063:web:8078bc24823541a4cb2772',
    messagingSenderId: '646751155063',
    projectId: 'frenzy-2a03e',
    authDomain: 'frenzy-2a03e.firebaseapp.com',
    storageBucket: 'frenzy-2a03e.appspot.com',
    measurementId: 'G-J1D08ZC5LQ',
  );

}