// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMqJkgwfY8Bm61sStEXgHbspqWrfA3tl4',
    appId: '1:396447708149:web:77f391016e29082132e6bc',
    messagingSenderId: '396447708149',
    projectId: 'frenzy-e7bbd',
    authDomain: 'frenzy-e7bbd.firebaseapp.com',
    storageBucket: 'frenzy-e7bbd.appspot.com',
    measurementId: 'G-VLEVH2XMNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs00yzo5XuuYno03OMPtptWJMJtSmYUWc',
    appId: '1:396447708149:android:6f7937234cbe881232e6bc',
    messagingSenderId: '396447708149',
    projectId: 'frenzy-e7bbd',
    storageBucket: 'frenzy-e7bbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFOyaY4j4vNgz9204PLM0ESJHt98Z_poY',
    appId: '1:396447708149:ios:06fc1d743869dd0e32e6bc',
    messagingSenderId: '396447708149',
    projectId: 'frenzy-e7bbd',
    storageBucket: 'frenzy-e7bbd.appspot.com',
    iosBundleId: 'com.example.frenzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFOyaY4j4vNgz9204PLM0ESJHt98Z_poY',
    appId: '1:396447708149:ios:06fc1d743869dd0e32e6bc',
    messagingSenderId: '396447708149',
    projectId: 'frenzy-e7bbd',
    storageBucket: 'frenzy-e7bbd.appspot.com',
    iosBundleId: 'com.example.frenzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMqJkgwfY8Bm61sStEXgHbspqWrfA3tl4',
    appId: '1:396447708149:web:642d3c9eea6b5f4432e6bc',
    messagingSenderId: '396447708149',
    projectId: 'frenzy-e7bbd',
    authDomain: 'frenzy-e7bbd.firebaseapp.com',
    storageBucket: 'frenzy-e7bbd.appspot.com',
    measurementId: 'G-0E7LD6ZLE6',
  );
}
